app:
  name: "douyin"
  mode: "dev"
  # 运行Gin的模式
  ip: "http://"
  port: 8080
  # 运行的端口
mysql:
  host: "127.0.0.1"
  port: 3306
  user: ""
  password: ""
  dbname: ""

log:
  level: "debug"
  filename: "../log/log.log"
  max_size: 200
  max_backups: 5
  max_age: 30

pprof:
  port: 6060
  host: "127.0.0.1"

redis:
  host: "127.0.0.1"
  post: 6379
  DB: 5

cos:
  url: ""
  sid: ""
  skey: ""